project:
  type: default
  render:
    - slides.qmd
  output-dir: docs

format:
  revealjs:
    theme: default
    transition: slide
    navigation-mode: linear
    slide-number: true
    chalkboard:
      buttons: false
    code-fold: true
    code-tools: true

